services:
    db:
        image: postgres:15.0
        container_name: redis-db
        environment:
            - POSTGRES_DB=redis-db
            - POSTGRES_USER=redis
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        volumes:
            - redis-db-pg:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        depends_on:
            - db

    api:
        container_name: api
        build:
            context: api
            dockerfile: dockerfile
        ports:
            - "6969:6969"
        command: sh -c "uvicorn main:app --host 0.0.0.0 --port 6969 --reload"
        volumes:
            - ./api/source:/app/redis-api
        depends_on:
            - db
            - redis
        env_file:
            - ./api/.env

volumes:
    redis-db-pg:
        driver: local
